<a href="https://colab.research.google.com/github/rasikacs23172/mechine-learning-tae/blob/main/model1_TAE1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, classification_report

In [25]:
from google.colab import files
uploaded = files.upload()

Saving student-mat.csv to student-mat (1).csv

In [26]:
import pandas as pd
df = pd.read_csv('student-mat.csv')
df.head()

  school;sex;age;address;famsize;Pstatus;Medu;Fedu;Mjob;Fjob;reason;guardian;traveltime;studytime;failures;schoolsup;famsup;paid;activities;nursery;higher;internet;romantic;famrel;freetime;goout;Dalc;Walc;health;absences;G1;G2;G3
0  GP;"F";18;"U";"GT3";"A";4;4;"at_home";"teacher...
1  GP;"F";17;"U";"GT3";"T";1;1;"at_home";"other";...
2  GP;"F";15;"U";"LE3";"T";1;1;"at_home";"other";...
3  GP;"F";15;"U";"GT3";"T";4;2;"health";"services...
4  GP;"F";16;"U";"GT3";"T";3;3;"other";"other";"h...

In [27]:
df = pd.read_csv('/content/student-mat.csv')

In [28]:
import os
print(os.listdir('/content'))

['.config', 'student+performance.zip', 'student-mat.csv', 'drive', 'student_performance_data', 'student-mat (1).csv', 'MACHINE LEARNING (LINEAR REGRESSION).html', 'sample_data']

In [29]:
import pandas as pd
df = pd.read_csv('student-mat.csv', sep=';')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,"GP;""F"";18;""U"";""GT3"";""A"";4;4;""at_home"";""teacher...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"GP;""F"";17;""U"";""GT3"";""T"";1;1;""at_home"";""other"";...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"GP;""F"";15;""U"";""LE3"";""T"";1;1;""at_home"";""other"";...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"GP;""F"";15;""U"";""GT3"";""T"";4;2;""health"";""services...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"GP;""F"";16;""U"";""GT3"";""T"";3;3;""other"";""other"";""h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         0 non-null      float64
 2   age         0 non-null      float64
 3   address     0 non-null      float64
 4   famsize     0 non-null      float64
 5   Pstatus     0 non-null      float64
 6   Medu        0 non-null      float64
 7   Fedu        0 non-null      float64
 8   Mjob        0 non-null      float64
 9   Fjob        0 non-null      float64
 10  reason      0 non-null      float64
 11  guardian    0 non-null      float64
 12  traveltime  0 non-null      float64
 13  studytime   0 non-null      float64
 14  failures    0 non-null      float64
 15  schoolsup   0 non-null      float64
 16  famsup      0 non-null      float64
 17  paid        0 non-null      float64
 18  activities  0 non-null      float64
 19  nursery     0 non-null      float64
 20  higher      0 non-null      float64
 21  internet    0 non-null      float64
 22  romantic    0 non-null      float64
 23  famrel      0 non-null      float64
 24  freetime    0 non-null      float64
 25  goout       0 non-null      float64
 26  Dalc        0 non-null      float64
 27  Walc        0 non-null      float64
 28  health      0 non-null      float64
 29  absences    0 non-null      float64
 30  G1          0 non-null      float64
 31  G2          0 non-null      float64
 32  G3          0 non-null      float64
dtypes: float64(32), object(1)
memory usage: 102.0+ KB

,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df.isnull().sum()

school          0
sex           395
age           395
address       395
famsize       395
Pstatus       395
Medu          395
Fedu          395
Mjob          395
Fjob          395
reason        395
guardian      395
traveltime    395
studytime     395
failures      395
schoolsup     395
famsup        395
paid          395
activities    395
nursery       395
higher        395
internet      395
romantic      395
famrel        395
freetime      395
goout         395
Dalc          395
Walc          395
health        395
absences      395
G1            395
G2            395
G3            395
dtype: int64

In [32]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

In [33]:
X = df.drop('G3', axis=1)
y = df['G3']

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

# Define the correct path to the student-mat.csv file.
path = 'student-mat.csv' # Assuming the file is in the current directory

# Define column names based on the dataset's structure.
col_names = [
    'school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
    'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures',
    'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet',
    'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences',
    'G1', 'G2', 'G3'
]

try:
    # Read the file as a single column, assuming no header, then manually split by semicolon
    df_raw = pd.read_csv(path, header=None, names=['full_row'])

    # Split the 'full_row' column by semicolon.
    df = df_raw['full_row'].str.split(';', expand=True)

    # The first row of `df` now contains the actual column headers. Set the first row as the new column names and drop the first row of data.
    df.columns = df.iloc[0]
    df = df[1:].reset_index(drop=True)

    # Convert relevant columns to appropriate numeric types, handling errors.
    # Also, strip quotes from string values if present, as seen in the raw data.
    for col in df.columns:
        if df[col].dtype == 'object':
            df[col] = df[col].astype(str).str.strip('"') # Strip double quotes
            try:
                df[col] = pd.to_numeric(df[col])
            except ValueError:
                # If conversion to numeric fails, it's likely a categorical string column; leave as object
                pass

    # Apply LabelEncoder to object columns (categorical features)
    le = LabelEncoder()
    for col in df.select_dtypes(include='object').columns:
        df[col] = le.fit_transform(df[col])

    # Feature and target selection
    X = df.drop('G3', axis=1)
    y = df['G3']

    # Handle remaining NaNs in features (X) by dropping all-NaN columns and imputing with column mean
    X = X.dropna(axis=1, how='all') # Drop columns that are entirely NaN
    # Impute remaining NaNs with column mean for numeric columns only
    for col in X.select_dtypes(include=np.number).columns:
        if X[col].isnull().any():
            X[col] = X[col].fillna(X[col].mean())

    # Ensure y does not have NaNs (e.g., if G3 was all NaN)
    y = y.dropna()
    # Align X and y after dropping NaNs from y
    X = X.loc[y.index]

    # Split data into training and testing sets
    # Check if there's enough data after cleanup
    if len(X) > 1 and len(y) > 1:
        X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

        # Standardize features
        scaler = StandardScaler()
        X_train = scaler.fit_transform(X_train)
        X_test = scaler.transform(X_test)

        # Train the Linear Regression model
        model = LinearRegression()
        model.fit(X_train, y_train)

        # Make predictions
        y_pred = model.predict(X_test)

        # Evaluate the model
        print("MSE:", mean_squared_error(y_test, y_pred))
        print("R2:", r2_score(y_test, y_pred))
    else:
        print("Error: Not enough valid data remaining after preprocessing to train the model.")

except FileNotFoundError:
    print(f"Error: The file at '{path}' was not found. Please verify the path.")
except Exception as e:
    print(f"An error occurred while loading or processing the CSV: {e}")

MSE: 5.032394108866746
R2: 0.7545777855043497

In [43]:
from sklearn.tree import DecisionTreeRegressor

# Initialize the model
# random_state ensures reproducibility
regressor = DecisionTreeRegressor(random_state=42)

# Fit the model
regressor.fit(X_train, y_train)

# Make predictions
predictions = regressor.predict(X_test)

In [44]:
# Limit the tree to 5 levels deep
regressor = DecisionTreeRegressor(max_depth=5, random_state=42)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=5, random_state=42)

In [45]:
# Each leaf must have at least 10 samples
regressor = DecisionTreeRegressor(min_samples_leaf=10, random_state=42)
regressor.fit(X_train, y_train)

DecisionTreeRegressor(min_samples_leaf=10, random_state=42)

In [46]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [3, 5, 10],
    'min_samples_split': [2, 5, 10],
    'criterion': ['squared_error', 'friedman_mse']
}

grid_search = GridSearchCV(DecisionTreeRegressor(), param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Best model found
best_model = grid_search.best_estimator_

In [47]:
from sklearn.tree import export_text

# Export the logic as a text-based tree
tree_rules = export_text(regressor, feature_names=list(X.columns))
print(tree_rules)

|--- G2 <= -0.04
|   |--- absences <= -0.58
|   |   |--- G2 <= -0.84
|   |   |   |--- freetime <= 0.28
|   |   |   |   |--- value: [0.00]
|   |   |   |--- freetime >  0.28
|   |   |   |   |--- value: [0.60]
|   |   |--- G2 >  -0.84
|   |   |   |--- age <= -0.19
|   |   |   |   |--- value: [9.82]
|   |   |   |--- age >  -0.19
|   |   |   |   |--- value: [4.00]
|   |--- absences >  -0.58
|   |   |--- G2 <= -0.84
|   |   |   |--- G2 <= -1.11
|   |   |   |   |--- value: [6.00]
|   |   |   |--- G2 >  -1.11
|   |   |   |   |--- value: [7.27]
|   |   |--- G2 >  -0.84
|   |   |   |--- G2 <= -0.31
|   |   |   |   |--- G2 <= -0.57
|   |   |   |   |   |--- value: [8.33]
|   |   |   |   |--- G2 >  -0.57
|   |   |   |   |   |--- Fjob <= 0.31
|   |   |   |   |   |   |--- Medu <= -0.22
|   |   |   |   |   |   |   |--- value: [9.70]
|   |   |   |   |   |   |--- Medu >  -0.22
|   |   |   |   |   |   |   |--- value: [9.20]
|   |   |   |   |   |--- Fjob >  0.31
|   |   |   |   |   |   |--- value: [8.80]
|   |   |   |--- G2 >  -0.31
|   |   |   |   |--- G1 <= -0.45
|   |   |   |   |   |--- value: [9.92]
|   |   |   |   |--- G1 >  -0.45
|   |   |   |   |   |--- value: [10.42]
|--- G2 >  -0.04
|   |--- G2 <= 0.76
|   |   |--- G2 <= 0.49
|   |   |   |--- G2 <= 0.23
|   |   |   |   |--- reason <= -0.63
|   |   |   |   |   |--- value: [11.21]
|   |   |   |   |--- reason >  -0.63
|   |   |   |   |   |--- value: [10.60]
|   |   |   |--- G2 >  0.23
|   |   |   |   |--- Walc <= -0.65
|   |   |   |   |   |--- value: [12.40]
|   |   |   |   |--- Walc >  -0.65
|   |   |   |   |   |--- Fjob <= 0.31
|   |   |   |   |   |   |--- value: [11.83]
|   |   |   |   |   |--- Fjob >  0.31
|   |   |   |   |   |   |--- value: [11.40]
|   |   |--- G2 >  0.49
|   |   |   |--- age <= -0.19
|   |   |   |   |--- value: [12.82]
|   |   |   |--- age >  -0.19
|   |   |   |   |--- value: [13.33]
|   |--- G2 >  0.76
|   |   |--- G2 <= 1.56
|   |   |   |--- G2 <= 1.03
|   |   |   |   |--- value: [14.12]
|   |   |   |--- G2 >  1.03
|   |   |   |   |--- G2 <= 1.29
|   |   |   |   |   |--- health <= 0.70
|   |   |   |   |   |   |--- value: [15.43]
|   |   |   |   |   |--- health >  0.70
|   |   |   |   |   |   |--- value: [15.10]
|   |   |   |   |--- G2 >  1.29
|   |   |   |   |   |--- value: [16.00]
|   |   |--- G2 >  1.56
|   |   |   |--- value: [18.27]